ansible_python_interpreter:  /usr/lpp/IBM/cyp/pyz/bin/python3
PYZ: /usr/lpp/IBM/cyp/pyz
ZOAU: /usr/lpp/IBM/zoautil
JAVA: /usr/lpp/java/java180/J8.0_64/bin
COBOL: /usr/lpp/cobol/cob630/igyv6r3/bin
STEPLIB: DFSF10.SDFSRESL

system_environment:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin:/usr/sbin:{{ JAVA }}:{{ COBOL }}"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  PYTHONSTDINENCODING: "cp1047"
  STEPLIB: "{{STEPLIB}}"