---
###############################################################################
# © Copyright IBM Corporation 2023
###############################################################################

# tasks file for issue_operator_cmd

##########################################################################
# Issue zos command
##########################################################################
- name: "{{ task_description }}"
  ibm.ibm_zos_core.zos_tso_command:
    commands: "{{command}}"
    max_rc: 4


