###############################################################################
# © Copyright IBM Corporation 2023
###############################################################################

- name: Create RACF CA Certificate
  hosts: all
  gather_facts: false
  environment: '{{ system_environment }}'

  tasks:
    - name: Set Owner Id
      set_fact: 
          owner_id: "{{ ansible_user | upper }}"

    - include_role:
        name: issue_tso_cmd
      vars:
        task_description: 'Create a new keyring'
        command:
          - RACDCERT ADDRING({{ keyring }}) ID({{ owner_id }})
          - RACDCERT LISTRING({{ keyring }}) ID({{ owner_id }})
      ignore_errors: true

    - include_role:
        name: issue_tso_cmd
      vars:
        task_description: 'Create new CA cert and connect to keyring'
        command:
          - RACDCERT GENCERT CERTAUTH KEYUSAGE(CERTSIGN) SUBJECTSDN(CN('{{ common_name }}') OU('{{ organizational_unit }}') C('{{ country }}')) WITHLABEL('{{ cert_label }}') NOTAFTER(DATE({{ expiry_date }}))
          - RACDCERT ID({{ owner_id }}) CONNECT(CERTAUTH LABEL('{{ cert_label }}') RING({{ keyring }}))
      when: not expiry_date == ''

    - include_role:
        name: issue_tso_cmd
      vars:
        task_description: 'Create new CA cert and connect to keyring'
        command:
          - RACDCERT GENCERT CERTAUTH KEYUSAGE(CERTSIGN) SUBJECTSDN(CN('{{ common_name }}') OU('{{ organizational_unit }}') C('{{ country }}')) WITHLABEL('{{ cert_label }}')
          - RACDCERT ID({{ owner_id }}) CONNECT(CERTAUTH LABEL('{{ cert_label }}') RING({{ keyring }}))
      when: expiry_date == ''
